GET http://localhost:3003/api/blogs/ HTTP/1.1
###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test Populate",
    "author": "Test",
    "url": "test.com",
    "userId": "62cb9c38d6275bd4c77b5713"
}
###

DELETE http://localhost:3003/api/blogs/62c51bb831a36b03bcdc15b0 HTTP/1.1
###
GET http://localhost:3003/api/users/ HTTP/1.1
###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "Test",
    "name": "Test",
    "password": "test"
}