GET http://localhost:3003/api/blogs/ HTTP/1.1
###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test Title",
    "author": "Test",
    "url": "test.com"
}
###

DELETE http://localhost:3003/api/blogs/62cbb8cc19c4760091ed6f4d HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6IjYyY2I5YzM4ZDYyNzViZDRjNzdiNTcxMyIsImlhdCI6MTY1NzUxNTMwOCwiZXhwIjoxNjU3NTE4OTA4fQ.QscoCWg6qg4bElpW3luQ11ytbCvMa_HSXqt2vCcilHM

###
GET http://localhost:3003/api/users/ HTTP/1.1
###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "Test",
    "name": "Test",
    "password": "test"
}

###
POST http://localhost:3003/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "Test",
    "password": "test"
}