GET http://localhost:3003/api/blogs/ HTTP/1.1
###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Bedbean Eats Cafe",
    "author": "Bedbean",
    "url": "test"
}
###

DELETE http://localhost:3003/api/blogs/62c51bb831a36b03bcdc15b0 HTTP/1.1
